var template=['			<!-- page6 -->',
'			<div class="pages page6 bg_style1" id="page6">',
'				<div class="bg_top pos_a">',
'					<img class="page_title page6_img2 opacity0" _src="img/page6_img2.png">',
'					<div class="page6_top_box pos_r pos_a_b">',
'						<img class="page6_blank" _src="img/page6_blank.png">',
'						<div class="page6_lines pos_a">',
'							<img class="line_b opacity0" _src="img/page6_line1.png">',
'							<div class="line_mask line_mask1 pos_a"></div>',
'							<div class="line_mask line_mask2 pos_a"></div>',
'						</div>',
'						<div class="page6_top_l pos_a">',
'							<img _src="img/page6_ej_l.png">',
'							<div class="page6_ej_mask pos_a"></div>',
'						</div>',
'						<div class="page6_top_r pos_a">',
'							<img _src="img/page6_ej_l.png">',
'							<div class="page6_ej_mask pos_a"></div>',
'						</div>',
'					</div>',
'					<img class="page6_img3 opacity0" _src="img/page6_img3.png">',
'				</div>',
'				<div class="bg_bottom pos_a">',
'					<img class="pos_a bg_line" _src="img/bg_line.png">',
'					<div class="page_solagn page6_img1 pos_a opacity0"><img _src="img/page6_img1.png"></div>',
'				</div>',
'				<!-- 人物 -->',
'				<div class="person_s2 pos_a opacity0"><div class="walk_steps walk_step0 pos_a"></div></div>',
'				<!-- 翻页 -->',
'				<section class="operation pos_a opacity0"><em id="pageIndex" class="pos_a">6</em><i id="totalNum" class="pos_a">21</i><b class="pos_a operatePre"></b><b class="pos_a operateNext"></b></section>',
'			</div>',
'			<!-- page7 -->',
'			<div class="pages page7 bg_style1" id="page7">',
'				<div class="bg_top pos_a">',
'					<div class="page7_top_box pos_a pos_a_b">',
'						<img class="page7_top_bg pos_r" _src="img/page7_top_bg.png">',
'						<div class="page7_top_l pos_a"><img class="pos_r" _src="img/page7_top_bg2_l.png"><div class="page7_mask2 pos_a"></div></div>',
'						<div class="page7_top_r pos_a"><img class="pos_r" _src="img/page7_top_bg2_r.png"><img class="page7_top_bg2_r2 pos_a opacity0" _src="img/page7_top_bg2_r2.png"><div class="page7_mask2 pos_a"></div></div>',
'						<div class="page7_mask_l pos_a"></div>',
'						<div class="page7_mask_r pos_a"></div>',
'						<img class="page7_num pos_a opacity0" _src="img/page7_num.png">',
'					</div>',
'				</div>',
'				<div class="bg_bottom pos_a">',
'					<img class="pos_a bg_line" _src="img/bg_line.png">',
'					<div class="page_solagn page7_img1 pos_a opacity0"><img _src="img/page7_img1.png"></div>',
'				</div>',
'				<!-- 人物 -->',
'				<div class="person_s2 pos_a opacity0"><div class="walk_steps walk_step0 pos_a"></div></div>',
'				<!-- 翻页 -->',
'				<section class="operation pos_a opacity0"><em id="pageIndex" class="pos_a">7</em><i id="totalNum" class="pos_a">21</i><b class="pos_a operatePre"></b><b class="pos_a operateNext"></b></section>',
'			</div>',
'			<!-- page8 -->',
'			<div class="pages page8 bg_style2" id="page8">',
'				<div class="bg_top pos_a">',
'					<div class="page8_top_box pos_a pos_a_b">',
'						<img class="page8_line3 pos_r opacity0" _src="img/page8_line3.png">',
'						<img class="page8_light pos_a opacity0" _src="img/page8_light.png">',
'						<img class="page8_txt pos_a opacity0" _src="img/page8_txt.png">',
'						<div class="bg_line page8_line1 pos_a">',
'							<img class="page8_line2_img pos_r" _src="img/page8_line1.png">',
'						</div>',
'						<div class="bg_line page8_line2 pos_a">',
'							<img class="page8_line2_img pos_r" _src="img/page8_line2.png">',
'							<div class="line2_mask line2_mask1 pos_a"></div>',
'							<div class="line2_mask line2_mask2 pos_a"></div>',
'						</div>',
'					</div>',
'				</div>',
'				<div class="bg_bottom pos_a">',
'					<img class="pos_a bg_line" _src="img/bg_line.png">',
'					<div class="page_solagn page8_img1 pos_a opacity0"><img _src="img/page8_img1.png"></div>',
'				</div>',
'				<!-- 人物 -->',
'				<div class="person_s2 pos_a opacity0"><div class="walk_steps walk_step0 pos_a"></div></div>',
'				<!-- 翻页 -->',
'				<section class="operation pos_a opacity0"><em id="pageIndex" class="pos_a">8</em><i id="totalNum" class="pos_a">21</i><b class="pos_a operatePre"></b><b class="pos_a operateNext"></b></section>',
'			</div>',
'			<!-- page9 -->',
'			<div class="pages page9 bg_style2" id="page9">',
'				<div class="bg_top pos_a">',
'					<img class="page_title page9_img2 opacity0" _src="img/page9_img2.png">',
'					<ul class="page9_top_box pos_a pos_a_b">',
'						<li class="page9_top_img1 pos_r"><img _src="img/page9_top_img1.png"><div class="page9_mask pos_a"></div></li>',
'						<li class="page9_top_img2 pos_r"><img _src="img/page9_top_img2.png"><div class="page9_mask pos_a"></div></li>',
'						<li class="page9_top_img3 pos_r"><img _src="img/page9_top_img3.png"><div class="page9_mask pos_a"></div></li>',
'						<li class="page9_top_img4 pos_r"><img _src="img/page9_top_img4.png"><div class="page9_mask pos_a"></div></li>',
'					</ul>',
'				</div>',
'				<div class="bg_bottom pos_a">',
'					<img class="pos_a bg_line" _src="img/bg_line.png">',
'					<div class="page_solagn page9_img1 pos_a opacity0"><img _src="img/page9_img1.png"></div>',
'				</div>',
'				<!-- 人物 -->',
'				<div class="person_s2 pos_a opacity0"><div class="walk_steps walk_step0 pos_a"></div></div>',
'				<!-- 翻页 -->',
'				<section class="operation pos_a opacity0"><em id="pageIndex" class="pos_a">9</em><i id="totalNum" class="pos_a">21</i><b class="pos_a operatePre"></b><b class="pos_a operateNext"></b></section>',
'			</div>',
'			<!-- page10 -->',
'			<div class="pages page10 bg_style2" id="page10">',
'				<div class="bg_top pos_a">',
'					<img class="page_title page10_img2 opacity0" _src="img/page10_img2.png">',
'					<div class="page10_top_box pos_a pos_a_b">',
'						<div class="page10_cont1 pos_r">',
'							<img class="page10_txt1 opacity0" _src="img/page10_txt1.png">',
'							<div class="cont_box cont_box1 pos_a opacity0">',
'								<ul class="pos_r">',
'									<li class="layer1 pos_a"><img _src="img/page10_bg1.png"></li>',
'									<li class="layer2 pos_a"><img _src="img/page10_bg2.png"></li>',
'									<li class="layer3 pos_a"><img _src="img/page10_bg3.png"></li>',
'								</ul>',
'							</div>',
'							<div class="cont_box cont_box2 pos_a opacity0">',
'								<ul class="pos_r">',
'									<li class="layer1 pos_a"><img _src="img/page10_bg1.png"></li>',
'									<li class="layer2 pos_a"><img _src="img/page10_bg2.png"></li>',
'									<li class="layer3 pos_a"><img _src="img/page10_bg3.png"></li>',
'								</ul>',
'							</div>',
'						</div>',
'						<div class="page10_cont2 pos_r">',
'							<img class="page10_txt2 opacity0" _src="img/page10_txt2.png">',
'							<div class="cont_box cont_box1 pos_a opacity0">',
'								<ul class="pos_r">',
'									<li class="layer1 pos_a"><img _src="img/page10_bg1.png"></li>',
'									<li class="layer2 pos_a"><img _src="img/page10_bg2.png"></li>',
'									<li class="layer3 pos_a"><img _src="img/page10_bg3.png"></li>',
'								</ul>',
'							</div>',
'							<div class="cont_box cont_box2 pos_a opacity0">',
'								<ul class="pos_r">',
'									<li class="layer1 pos_a"><img _src="img/page10_bg1.png"></li>',
'									<li class="layer2 pos_a"><img _src="img/page10_bg2.png"></li>',
'									<li class="layer3 pos_a"><img _src="img/page10_bg3.png"></li>',
'								</ul>',
'							</div>',
'						</div>',
'					</div>',
'				</div>',
'				<div class="bg_bottom pos_a">',
'					<img class="pos_a bg_line" _src="img/bg_line.png">',
'					<div class="page_solagn page10_img1 pos_a opacity0"><img _src="img/page10_img1.png"></div>',
'				</div>',
'				<!-- 人物 -->',
'				<div class="person_s2 pos_a opacity0"><div class="walk_steps walk_step0 pos_a"></div></div>',
'				<!-- 翻页 -->',
'				<section class="operation pos_a opacity0"><em id="pageIndex" class="pos_a">10</em><i id="totalNum" class="pos_a">21</i><b class="pos_a operatePre"></b><b class="pos_a operateNext"></b></section>',
'			</div>',
'			<!-- page11 -->',
'			<div class="pages page11 bg_style2" id="page11">',
'				<div class="bg_top pos_a">',
'					<img class="page_title page11_img2 opacity0" _src="img/page11_img2.png">',
'					<div class="page11_top_box pos_a pos_a_b">',
'						<img class="page11_top_img1 pos_r" _src="img/page11_top_img1.png">',
'						<div class="page11_mask page11_top_img1_mask pos_a"></div>',
'						<img class="page11_top_img2 pos_a" _src="img/page11_top_img2.png">',
'						<div class="page11_mask page11_top_img2_mask pos_a"></div>',
'						<img class="page11_top_img4 pos_a" _src="img/page11_top_img4.png">',
'						<div class="page11_mask page11_top_img4_mask pos_a"></div>',
'						<div class="page11_top_img3_box pos_a"></div>',
'					</div>',
'				</div>',
'				<div class="bg_bottom pos_a">',
'					<img class="pos_a bg_line" _src="img/bg_line.png">',
'					<div class="page_solagn page11_img1 pos_a opacity0"><img _src="img/page11_img1.png"></div>',
'				</div>',
'				<!-- 人物 -->',
'				<div class="person_s2 pos_a opacity0"><div class="walk_steps walk_step0 pos_a"></div></div>',
'				<!-- 翻页 -->',
'				<section class="operation pos_a opacity0"><em id="pageIndex" class="pos_a">11</em><i id="totalNum" class="pos_a">21</i><b class="pos_a operatePre"></b><b class="pos_a operateNext"></b></section>',
'			</div>',
'			<!-- page12 -->',
'			<div class="pages page12 bg_style2" id="page12">',
'				<div class="bg_top pos_a">',
'					<img class="page_title page12_img2 opacity0" _src="img/page12_img2.png">',
'					<div class="page12_top_box">',
'						<div class="page12_top_l pos_a">',
'							<ul class="page12_ring ring1 pos_r opacity0">',
'								<li class="layer1 pos_r"><img _src="img/page12_bg1.png"></li>',
'								<li class="layer2 pos_a"><img _src="img/page12_bg2.png"></li>',
'								<li class="layer3 pos_a"><img _src="img/page12_bg3.png"></li>',
'								<li class="layer4 pos_a"><img _src="img/page12_txt1.png"><div class="page12_mask pos_a"></div></li>',
'							</ul>',
'							<ul class="page12_ring ring2 pos_r opacity0">',
'								<li class="layer1 pos_r"><img _src="img/page12_bg1.png"></li>',
'								<li class="layer2 pos_a"><img _src="img/page12_bg2.png"></li>',
'								<li class="layer3 pos_a"><img _src="img/page12_bg3.png"></li>',
'								<li class="layer4 pos_a"><img _src="img/page12_txt2.png"><div class="page12_mask pos_a"></div></li>',
'							</ul>',
'						</div>',
'						<div class="page12_top_r pos_a">',
'							<ul class="page12_ring ring3 pos_r opacity0">',
'								<li class="layer1 pos_r"><img _src="img/page12_bg1.png"></li>',
'								<li class="layer2 pos_a"><img _src="img/page12_bg2.png"></li>',
'								<li class="layer3 pos_a"><img _src="img/page12_bg3.png"></li>',
'								<li class="layer4 pos_a"><img _src="img/page12_txt3.png"><div class="page12_mask pos_a"></div></li>',
'							</ul>',
'							<ul class="page12_ring ring4 pos_r opacity0">',
'								<li class="layer1 pos_r"><img _src="img/page12_bg1.png"></li>',
'								<li class="layer2 pos_a"><img _src="img/page12_bg2.png"></li>',
'								<li class="layer3 pos_a"><img _src="img/page12_bg3.png"></li>',
'								<li class="layer4 pos_a"><img _src="img/page12_txt4.png"><div class="page12_mask pos_a"></div></li>',
'							</ul>',
'						</div>',
'					</div>',
'				</div>',
'				<div class="bg_bottom pos_a">',
'					<img class="pos_a bg_line" _src="img/bg_line.png">',
'					<div class="page_solagn page12_img1 pos_a opacity0"><img _src="img/page12_img1.png"></div>',
'				</div>',
'				<!-- 人物 -->',
'				<div class="person_s2 pos_a opacity0"><div class="walk_steps walk_step0 pos_a"></div></div>',
'				<!-- 翻页 -->',
'				<section class="operation pos_a opacity0"><em id="pageIndex" class="pos_a">12</em><i id="totalNum" class="pos_a">21</i><b class="pos_a operatePre"></b><b class="pos_a operateNext"></b></section>',
'			</div>',
'			<!-- page13 -->',
'			<div class="pages page13 bg_style2" id="page13">',
'				<div class="bg_top pos_a">',
'					<img class="page_title page13_img2 opacity0" _src="img/page13_img2.png">',
'					<div class="page13_top_box pos_a pos_a_b">',
'						<div class="page13_item item1 pos_a">',
'							<img class="page13_top_txt" _src="img/page13_top_txt1.png" />',
'							<div class="page13_mask1 pos_a"></div>',
'							<img class="page13_top_bg pos_a" _src="img/page13_top_bg1.png" />',
'							<div class="page13_mask2 pos_a"></div>',
'						</div>',
'						<div class="page13_item item2 pos_a">',
'							<img class="page13_top_txt" _src="img/page13_top_txt2.png" />',
'							<div class="page13_mask1 pos_a"></div>',
'							<img class="page13_top_bg pos_a" _src="img/page13_top_bg2.png" />',
'							<div class="page13_mask2 pos_a"></div>',
'						</div>',
'						<div class="page13_item item3 pos_a">',
'							<img class="page13_top_txt" _src="img/page13_top_txt3.png" />',
'							<div class="page13_mask1 pos_a"></div>',
'							<img class="page13_top_bg pos_a" _src="img/page13_top_bg3.png" />',
'							<div class="page13_mask2 pos_a"></div>',
'						</div>',
'						<div class="page13_item item4 pos_a">',
'							<img class="page13_top_txt" _src="img/page13_top_txt4.png" />',
'							<div class="page13_mask1 pos_a"></div>',
'							<img class="page13_top_bg pos_a" _src="img/page13_top_bg4.png" />',
'							<div class="page13_mask2 pos_a"></div>',
'						</div>',
'					</div>',
'				</div>',
'				<div class="bg_bottom pos_a">',
'					<img class="pos_a bg_line" _src="img/bg_line.png">',
'					<div class="page_solagn page13_img1 pos_a opacity0"><img _src="img/page13_img1.png"></div>',
'				</div>',
'				<!-- 人物 -->',
'				<div class="person_s2 pos_a opacity0"><div class="walk_steps walk_step0 pos_a"></div></div>',
'				<!-- 翻页 -->',
'				<section class="operation pos_a opacity0"><em id="pageIndex" class="pos_a">13</em><i id="totalNum" class="pos_a">21</i><b class="pos_a operatePre"></b><b class="pos_a operateNext"></b></section>',
'			</div>',
'			<!-- page14 -->',
'			<div class="pages page14 bg_style2" id="page14">',
'				<div class="bg_top pos_a">',
'					<img class="page_title page14_img2 opacity0" _src="img/page14_img2.png">',
'					<div class="page14_top_box pos_a pos_a_b">',
'						<div class="page14_item item1 pos_a">',
'							<ul class="page14_ico_box">',
'								<li><img class="page14_ico opacity0" _src="img/page14_ico.png"></li>',
'								<li><img class="page14_ico opacity0" _src="img/page14_ico.png"></li>',
'								<li><img class="page14_ico opacity0" _src="img/page14_ico.png"></li>',
'								<li><img class="page14_ico opacity0" _src="img/page14_ico.png"></li>',
'								<li><img class="page14_ico opacity0" _src="img/page14_ico.png"></li>',
'							</ul>',
'						</div>',
'						<div class="page14_item item2 pos_a">',
'							<img class="page14_txt" _src="img/page14_txt1.png"><div class="page14_mask pos_a"></div>',
'						</div>',
'						<div class="page14_item item3 pos_a">',
'							<img class="page14_txt" _src="img/page14_txt2.png"><div class="page14_mask pos_a"></div>',
'						</div>',
'						<div class="page14_item item4 pos_a">',
'							<ul class="page14_ico_box">',
'								<li><img class="page14_ico opacity0" _src="img/page14_ico.png"></li>',
'								<li><img class="page14_ico opacity0" _src="img/page14_ico.png"></li>',
'								<li><img class="page14_ico opacity0" _src="img/page14_ico.png"></li>',
'								<li><img class="page14_ico opacity0" _src="img/page14_ico.png"></li>',
'								<li><img class="page14_ico opacity0" _src="img/page14_ico.png"></li>',
'							</ul>',
'						</div>',
'					</div>',
'				</div>',
'				<div class="bg_bottom pos_a">',
'					<img class="pos_a bg_line" _src="img/bg_line.png">',
'					<div class="page_solagn page14_img1 pos_a opacity0"><img _src="img/page14_img1.png"></div>',
'				</div>',
'				<!-- 人物 -->',
'				<div class="person_s2 pos_a opacity0"><div class="walk_steps walk_step0 pos_a"></div></div>',
'				<!-- 翻页 -->',
'				<section class="operation pos_a opacity0"><em id="pageIndex" class="pos_a">14</em><i id="totalNum" class="pos_a">21</i><b class="pos_a operatePre"></b><b class="pos_a operateNext"></b></section>',
'			</div>',
'			<!-- page15 -->',
'			<div class="pages page15 bg_style2" id="page15">',
'				<div class="bg_top pos_a">',
'					<img class="page_title page15_img2 opacity0" _src="img/page15_img2.png">',
'					<div class="page15_top_box pos_a">',
'						<img class="page15_bg2" _src="img/page15_bg2.png">',
'						<div class="page15_mask1_box pos_a">',
'							<div class="maske1 pos_a"></div>',
'							<div class="maske2 pos_a"></div>',
'						</div>',
'						<img class="page15_bg pos_a" _src="img/page15_bg.png">',
'						<div class="page15_mask2_box pos_a">',
'							<div class="maske1 pos_a"></div>',
'							<div class="maske2 pos_a"></div>',
'						</div>',
'						<div class="page15_mask3_box pos_a">',
'							<div class="maske1 pos_a"></div>',
'							<div class="maske2 pos_a"></div>',
'						</div>',
'						<img class="page15_txt txt1 pos_a opacity0" _src="img/page15_txt1.png">',
'						<img class="page15_txt txt2 pos_a opacity0" _src="img/page15_txt2.png">',
'						<img class="page15_txt txt3 pos_a opacity0" _src="img/page15_txt3.png">',
'					</div>',
'				</div>',
'				<div class="bg_bottom pos_a">',
'					<img class="pos_a bg_line" _src="img/bg_line.png">',
'					<div class="page_solagn page15_img1 pos_a opacity0"><img _src="img/page15_img1.png"></div>',
'				</div>',
'				<!-- 人物 -->',
'				<div class="person_s2 pos_a opacity0"><div class="walk_steps walk_step0 pos_a"></div></div>',
'				<!-- 翻页 -->',
'				<section class="operation pos_a opacity0"><em id="pageIndex" class="pos_a">15</em><i id="totalNum" class="pos_a">21</i><b class="pos_a operatePre"></b><b class="pos_a operateNext"></b></section>',
'			</div>',
'			<!-- page16 -->',
'			<div class="pages page16 bg_style2" id="page16">',
'				<div class="bg_top pos_a">',
'					<img class="page_title page16_img2 opacity0" _src="img/page16_img2.png">',
'					<div class="page16_top_box pos_a pos_a_b">',
'						<div class="page16_item item1 pos_a">',
'							<img class="page16_txt opacity0" _src="img/page16_txt1.png">',
'							<div class="flower_box pos_r">',
'								<img class="page16_line" _src="img/page16_line1.png">',
'								<div class="line_mask pos_a"></div>',
'								<img class="flower pos_a opacity0" _src="img/page16_flower.png">',
'								<img class="leaf leafL leaf1 pos_a opacity0" _src="img/page16_leaf_l.png">',
'								<img class="leaf leafR leaf2 pos_a opacity0" _src="img/page16_leaf_r.png">',
'								<img class="leaf leafL leaf3 big_leaf pos_a opacity0" _src="img/page16_leaf_l.png">',
'								<img class="leaf leafR leaf4 big_leaf pos_a opacity0" _src="img/page16_leaf_r.png">',
'								<img class="leaf leafL leaf5 small_leaf pos_a opacity0" _src="img/page16_leaf_l.png">',
'								<img class="leaf leafR leaf6 small_leaf pos_a opacity0" _src="img/page16_leaf_r.png">',
'							</div>',
'						</div>',
'						<div class="page16_item item2 pos_a">',
'							<img class="page16_txt opacity0" _src="img/page16_txt2.png">',
'							<div class="flower_box pos_r">',
'								<img class="page16_line" _src="img/page16_line2.png">',
'								<div class="line_mask pos_a"></div>',
'								<img class="flower pos_a opacity0" _src="img/page16_flower.png">',
'								<img class="leaf leafL leaf1 pos_a opacity0" _src="img/page16_leaf_l.png">',
'								<img class="leaf leafR leaf2 pos_a opacity0" _src="img/page16_leaf_r.png">',
'								<img class="leaf leafL leaf3 small_leaf pos_a opacity0" _src="img/page16_leaf_l.png">',
'								<img class="leaf leafR leaf4 small_leaf pos_a opacity0" _src="img/page16_leaf_r.png">',
'							</div>',
'						</div>',
'						<div class="page16_item item3 pos_a">',
'							<img class="page16_txt opacity0" _src="img/page16_txt3.png">',
'							<div class="flower_box pos_r">',
'								<img class="page16_line" _src="img/page16_line3.png">',
'								<div class="line_mask pos_a"></div>',
'								<img class="flower pos_a opacity0" _src="img/page16_flower.png">',
'								<img class="leaf leafL leaf3 small_leaf pos_a opacity0" _src="img/page16_leaf_l.png">',
'								<img class="leaf leafR leaf4 small_leaf pos_a opacity0" _src="img/page16_leaf_r.png">',
'							</div>',
'						</div>',
'						<div class="page16_item item4 pos_a">',
'							<img class="page16_txt opacity0" _src="img/page16_txt4.png">',
'							<div class="flower_box pos_r">',
'								<img class="page16_line" _src="img/page16_line4.png">',
'								<div class="line_mask pos_a"></div>',
'								<img class="leaf leafL leaf3 small_leaf pos_a opacity0" _src="img/page16_leaf_l.png">',
'								<img class="leaf leafR leaf4 small_leaf pos_a opacity0" _src="img/page16_leaf_r.png">',
'							</div>',
'						</div>',
'					</div>',
'				</div>',
'				<div class="bg_bottom pos_a">',
'					<img class="pos_a bg_line" _src="img/bg_line.png">',
'					<div class="page_solagn page16_img1 pos_a opacity0"><img _src="img/page16_img1.png"></div>',
'				</div>',
'				<!-- 人物 -->',
'				<div class="person_s2 pos_a opacity0"><div class="walk_steps walk_step0 pos_a"></div></div>',
'				<!-- 翻页 -->',
'				<section class="operation pos_a opacity0"><em id="pageIndex" class="pos_a">16</em><i id="totalNum" class="pos_a">21</i><b class="pos_a operatePre"></b><b class="pos_a operateNext"></b></section>',
'			</div>',
'			<!-- page17 -->',
'			<div class="pages page17 bg_style3" id="page17">',
'				<div class="bg_top pos_a">',
'					<div class="page17_top_box pos_a pos_a_b"><img class="page17_top_bg opacity0" _src="img/page17_top_bg.png"></div>',
'				</div>',
'				<div class="bg_bottom pos_a">',
'					<img class="pos_a bg_line" _src="img/bg_line.png">',
'					<div class="page_solagn page17_img1 pos_a opacity0"><img _src="img/page17_img1.png"></div>',
'				</div>',
'				<div class="page17_person pos_a opacity0"><img _src="img/page17_person.png"></div>',
'				<!-- 人物 -->',
'				<div class="person_s2 pos_a opacity0"><div class="walk_steps walk_step0 pos_a"></div></div>',
'				<!-- 翻页 -->',
'				<section class="operation pos_a opacity0"><em id="pageIndex" class="pos_a">17</em><i id="totalNum" class="pos_a">21</i><b class="pos_a operatePre"></b><b class="pos_a operateNext"></b></section>',
'			</div>',
'			<!-- page18 -->',
'			<div class="pages page18 bg_style3" id="page18">',
'				<div class="bg_top pos_a">',
'					<div class="page18_top_box pos_a">',
'						<img class="page18_bg1 opacity0" _src="img/page18_bg1.png">',
'						<img class="page18_bg2 pos_a opacity0" _src="img/page18_bg2.png">',
'						<img class="page18_bg3 pos_a opacity0" _src="img/page18_bg3.png">',
'						<img class="page18_bg4 pos_a opacity0" _src="img/page18_bg4.png">',
'						<div class="page18_head pos_a opacity0"><img _src="img/page18_head.png"></div>',
'					</div>',
'				</div>',
'				<div class="bg_bottom pos_a">',
'					<img class="pos_a bg_line" _src="img/bg_line.png">',
'					<div class="page_solagn page18_img1 pos_a opacity0"><img _src="img/page18_img1.png"></div>',
'				</div>',
'				<!-- 翻页 -->',
'				<section class="operation pos_a opacity0"><em id="pageIndex" class="pos_a">18</em><i id="totalNum" class="pos_a">21</i><b class="pos_a operatePre"></b><b class="pos_a operateNext"></b></section>',
'			</div>',
'			<!-- page19 -->',
'			<div class="pages page19 bg_style3" id="page19">',
'				<div class="bg_top pos_a">',
'					<div class="page18_top_box pos_a">',
'						<img class="page18_bg1 opacity0" _src="img/page18_bg1.png">',
'						<img class="page18_bg2 pos_a opacity0" _src="img/page18_bg2.png">',
'						<img class="page18_bg3 pos_a opacity0" _src="img/page18_bg3.png">',
'						<img class="page18_bg4 pos_a opacity0" _src="img/page18_bg4.png">',
'						<div class="page18_head pos_a opacity0"><img _src="img/page19_head.png"></div>',
'					</div>',
'				</div>',
'				<div class="bg_bottom pos_a">',
'					<img class="pos_a bg_line" _src="img/bg_line.png">',
'					<div class="page_solagn page19_img1 pos_a opacity0"><img _src="img/page19_img1.png"></div>',
'				</div>',
'				<!-- 翻页 -->',
'				<section class="operation pos_a opacity0"><em id="pageIndex" class="pos_a">19</em><i id="totalNum" class="pos_a">21</i><b class="pos_a operatePre"></b><b class="pos_a operateNext"></b></section>',
'			</div>',
'			<!-- page20 -->',
'			<div class="pages page20 bg_style3" id="page20">',
'				<div class="bg_top pos_a">',
'					<div class="page18_top_box pos_a">',
'						<img class="page18_bg1 opacity0" _src="img/page18_bg1.png">',
'						<img class="page18_bg2 pos_a opacity0" _src="img/page18_bg2.png">',
'						<img class="page18_bg3 pos_a opacity0" _src="img/page18_bg3.png">',
'						<img class="page18_bg4 pos_a opacity0" _src="img/page18_bg4.png">',
'						<div class="page18_head pos_a opacity0"><img _src="img/page20_head.png"></div>',
'					</div>',
'				</div>',
'				<div class="bg_bottom pos_a">',
'					<img class="pos_a bg_line" _src="img/bg_line.png">',
'					<div class="page_solagn page20_img1 pos_a opacity0"><img _src="img/page20_img1.png"></div>',
'				</div>',
'				<!-- 翻页 -->',
'				<section class="operation pos_a opacity0"><em id="pageIndex" class="pos_a">20</em><i id="totalNum" class="pos_a">21</i><b class="pos_a operatePre"></b><b class="pos_a operateNext"></b></section>',
'			</div>',
'			<!-- page21 -->',
'			<div class="pages page21 bg_style3" id="page21">',
'				<div class="bg_top pos_a">',
'					<img class="page21_share_weixin" _src="img/page21_share_weixin.png">',
'					<img class="page21_img2 pos_a opacity0" _src="img/page21_img2.png">',
'					<img class="page18_bg3 pos_a opacity0" _src="img/page18_bg3.png">',
'					<img class="page18_bg4 pos_a opacity0" _src="img/page18_bg4.png">',
'					<div class="page21_top_box pos_a pos_a_b">',
'						<img class="page21_img1 opacity0" _src="img/page21_img1.png">',
'					</div>',
'				</div>',
'				<div class="bg_bottom pos_a">',
'					<img class="pos_a bg_line" _src="img/bg_line.png">',
'					<div class="other_share_box">',
'						<img class="page21_img3 opacity0" _src="img/page21_img3.png">',
'						<div class="other_share">',
'							<div class="share_l f_l">',
'								<div class="share_ico ico1 opacity0"><a id="share_sina" href="javascript:;" title="分享到新浪微博"><img _src="img/page21_share_ico1.png"></a></div>',
'								<div class="share_name name1 opacity0"><img _src="img/page21_share_name1.png"></div>',
'								<div class="share_ico ico2 opacity0"><a id="share_douban" href="javascript:;" title="分享到豆瓣"><img _src="img/page21_share_ico2.png"></a></div>',
'								<div class="share_name name2 opacity0"><img _src="img/page21_share_name2.png"></div>',
'							</div>',
'							<div class="share_r f_r">',
'								<div class="share_ico ico1 opacity0"><a id="share_qqwb" href="javascript:;" title="分享到腾讯"><img _src="img/page21_share_ico3.png"></a></div>',
'								<div class="share_name name1 opacity0"><img _src="img/page21_share_name3.png"></div>',
'								<div class="share_ico ico1 opacity0"><a id="share_renren" href="javascript:;" title="分享到人人"><img _src="img/page21_share_ico4.png"></a></div>',
'								<div class="share_name name2 opacity0"><img _src="img/page21_share_name4.png"></div>',
'							</div>',
'						</div>',
'					</div>',
'					<div class="weixin_share_box">',
'						<img class="page21_img4 opacity0" _src="img/page21_img4.png">',
'						</div>',
'					</div>',
'				</div>',
'			</div>'].join("");
